trigger:
  batch: true
  branches:
    include:
      - "*"

variables:
  - name: buildConfiguration
    value: 'release'
  - name: buildPlatform
    value: 'anycpu'
  - group: 'Prod Management Resources'

resources:
  repositories:
    - repository: das-platform-building-blocks
      type: github
      name: SkillsFundingAgency/das-platform-building-blocks
      ref: refs/heads/master
      endpoint: 'GitHub (SFA)'

pool:
  name: 'DAS - Continuous Integration'

workspace:
  clean: all

steps:
  - task: UseGitVersion@5
    inputs:
      versionSpec: 5.x
      useConfigFile: true
      configFilePath: GitVersion.yml

  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: 'src/**/*.csproj'

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects: 'src/**/*.csproj'
      arguments: '--configuration $(buildConfiguration) --no-restore'

  - task: DotNetCoreCLI@2
    displayName: Test
    inputs:
      command: test
      projects: '**/*.UnitTests.csproj'

  - template: azure-pipelines-templates/dependency-check.yml@das-platform-building-blocks

  - task: DotNetCoreCLI@2
    displayName: Publish Web App
    inputs:
      command: publish
      publishWebProjects: true
      projects: 'src/SFA.DAS.RoatpOversight.Web/SFA.DAS.RoatpOversight.Web.csproj'
      arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)/publish --no-restore --no-build'

  - task: CopyFiles@2
    displayName: 'Copy files to: $(build.artifactstagingdirectory)'
    inputs:
      contents: |
        azure/**
      targetFolder: $(build.artifactstagingdirectory)/publish

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact'
    inputs:
      pathToPublish: '$(build.artifactstagingdirectory)/publish'